version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python3jupyter
    volumes:
      - /home/adelie/jupyter_notebook/notebooks:/home/jovyan
    ports:
      - 8888:8888
      - 9000:9000
    environment:
      - GRANT_SUDO=yes